AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  InlineLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.12
      PackageType: Zip
      InlineCode: |
        def handler(event, context):
            message = 'Hello {} {}!'.format(event['first_name'], event['last_name'])  
            print("Log this for me")
            return { 
                'message' : message
            }