#!/usr/bin/env bash

echo "== deploy Data Firehose with an s3 bucket via CFN"

STACK_NAME="dataf-1212"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy/index.html
aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region ca-central-1 \
--stack-name $STACK_NAME