AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  InlineLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function.handler
      Runtime: python3.12
      PackageType: Zip
      CodeUri: "./function/"
      Layers:
        - arn:aws:lambda:ca-central-1:982383527471:layer:faker-py-layer:2