#!/usr/bin/env bash

# Check if the argument is not provided
if [ -z "$1" ]; then
  echo "Argument not provided."
else
  export VPC_ID="$1"
fi


# detach the IGW

# delete the IGW

# delete vpc

aws ec2 delete-vpc --vpc-id $VPC_ID