INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
('What does AWS stand for?', 'Adobe Web Services', 'Amazon Web Services', 'Apple Web Services', 'Automated Web Services', 'B'),
('Which AWS service is used for object storage?', 'Amazon EC2', 'Amazon RDS', 'Amazon S3', 'Amazon Lambda', 'C'),
('What is Amazon EC2 used for?', 'Manage relational databases', 'Cloud storage', 'Compute capacity management', 'Machine learning', 'C'),
('Which service is a managed NoSQL database?', 'Amazon S3', 'Amazon DynamoDB', 'Amazon Redshift', 'Amazon SQS', 'B'),
('What does Amazon RDS stand for?', 'Relational Database Service', 'Realtime Data Service', 'Reliable Datastore Service', 'Rapid Data Storage', 'A'),
('Which AWS service provides a virtual network?', 'Amazon VPC', 'Amazon EC2', 'Amazon Route 53', 'Amazon Connect', 'A'),
('What is the main purpose of Amazon S3?', 'Compute capacity', 'Load balancing', 'Data storage', 'Network routing', 'C'),
('Which AWS service is used for content delivery and caching?', 'Amazon EC2', 'Amazon RDS', 'Amazon S3', 'Amazon CloudFront', 'D'),
('What kind of model is AWS pricing based on?', 'Subscription', 'Pay-as-you-go', 'Fixed rate', 'Freemium', 'B'),
('Which AWS service allows for serverless function execution?', 'Amazon EC2', 'Amazon RDS', 'AWS Lambda', 'Amazon S3', 'C'),
('What tool does AWS offer for managing user access?', 'Amazon IAM', 'Amazon SES', 'Amazon VPC', 'Amazon SQS', 'A'),
('Which AWS product is a global DNS web service?', 'Amazon VPC', 'Amazon EC2', 'Amazon Route 53', 'Amazon S3', 'C'),
('What does Amazon EBS stand for?', 'Elastic Block Store', 'Elastic Business Service', 'Extended Bucket Storage', 'Elastic Backup Service', 'A'),
('Which service is primarily used for data warehousing?', 'Amazon RDS', 'Amazon EC2', 'Amazon DynamoDB', 'Amazon Redshift', 'D'),
('Which AWS service is ideal for big data analysis?', 'Amazon EMR', 'Amazon EC2', 'Amazon CloudSearch', 'Amazon S3', 'A'),
('What is the main benefit of AWS Auto Scaling?', 'Increased security', 'Cost reduction', 'Traffic balancing', 'Data encryption', 'B'),
('Which service handles large scale email sending?', 'Amazon SES', 'Amazon EC2', 'Amazon S3', 'Amazon VPC', 'A'),
('What is Amazon SQS?', 'Storage Queue Service', 'Simple Queue Service', 'Superior Quality Service', 'Simple Quality Service', 'B'),
('What does the ''A'' in Amazon Aurora stand for?', 'Automated', 'Aurora', 'Amazon', 'Advanced', 'D'),
('Which AWS service helps in disaster recovery planning?', 'Amazon Glacier', 'Amazon RDS', 'Amazon S3', 'Amazon EC2', 'A');